project_id = "buwtnkxkrtpnouompkap"
[functions.anthropic-questions]
enabled = true
verify_jwt = false
entrypoint = "./functions/anthropic-questions/index.ts"

[functions.anthropic-recommendations]
enabled = true
verify_jwt = false
entrypoint = "./functions/anthropic-recommendations/index.ts"

[functions.tmdb-proxy]
enabled = true
verify_jwt = false
import_map = "./functions/tmdb-proxy/import_map.json"
entrypoint = "./functions/tmdb-proxy/index.ts"

[functions.google-books-proxy]
enabled = true
verify_jwt = false
import_map = "./functions/google-books-proxy/import_map.json"
entrypoint = "./functions/google-books-proxy/index.ts"
